import * as React from 'react'
import {
  ArrowLeftRight,
  ArrowRight,
  Bell,
  BookOpen,
  Box,
  ChartNoAxesColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDashed,
  CircleDollarSign,
  CircleHelp,
  Clock3,
  CreditCard,
  Database,
  Eye,
  Gift,
  Github,
  Globe2,
  Inbox,
  LayoutGrid,
  Lightbulb,
  LogOut,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  ShieldCheck,
  Trash2,
  TriangleAlert,
  UserRoundPlus,
  UsersRound,
  WalletCards,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const icons = {
  arrow: ArrowRight,
  bell: Bell,
  bolt: Zap,
  book: BookOpen,
  card: CreditCard,
  chart: ChartNoAxesColumn,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock3,
  creditCard: CreditCard,
  cube: Box,
  database: Database,
  dollar: CircleDollarSign,
  edit: Pencil,
  error: TriangleAlert,
  eye: Eye,
  gift: Gift,
  github: Github,
  globe: Globe2,
  grid: LayoutGrid,
  help: CircleHelp,
  inbox: Inbox,
  key: UserRoundPlus,
  lightbulb: Lightbulb,
  link: ArrowLeftRight,
  logout: LogOut,
  money: CircleDollarSign,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  shield: ShieldCheck,
  trash: Trash2,
  userPlus: UserRoundPlus,
  users: UsersRound,
  wallet: WalletCards,
  x: X,
} satisfies Record<string, LucideIcon>

export type AppIconName = keyof typeof icons

export function AppIcon({ name, className = 'size-4' }: { name: AppIconName; className?: string }) {
  const Icon = icons[name] || CircleDashed
  return <Icon className={className} aria-hidden="true" />
}
